version: '3'
services:
 mysql:
  container_name: mysql
  image: mysql
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  volumes:
   - mysql_data:/var/lib/mysql
  ports:
   - 13306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=changeme
   - MYSQL_DATABASE=logicaldoc
   - MYSQL_USER=ldoc
   - MYSQL_PASSWORD=changeme

 logicaldoc:     
  container_name: logicaldoc-ce
  image: logicaldoc/logicaldoc-ce
  depends_on:
   - mysql
  command: ["./wait-for-it.sh", "mysql:3306", "-t", "30", "--", "/opt/logicaldoc/start-logicaldoc.sh", "run"]
  ports:
   - 8080:8080
  environment:
   - LDOC_MEMORY=2000
   - DB_HOST=mysql
   - DB_NAME=logicaldoc
   - DB_USER=ldoc
   - DB_PASSWORD=changeme
  volumes:
   - ldoc_conf:/opt/logicaldoc/conf
   - ldoc_repository:/opt/logicaldoc/repository
   - /mnt/LogicalDOC/doc:/opt/logicaldoc/repository/doc
  ulimits:
    nproc: 65535
    nofile:
      soft: 6000
      hard: 40000

volumes:
  mysql_data:
  ldoc_conf:
  ldoc_repository:
